// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oujakopwvomsygkvjnfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91amFrb3B3dm9tc3lna3ZqbmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTMwNDAsImV4cCI6MjA2NDY4OTA0MH0.XgHk9DZY8ZPyoHUlcD-5cKL_J5bS5Psu41DNvTJA6Fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);